apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin-user-scram
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  authentication:
    type: scram-sha-512
  # super-users do not declare authorization block