#
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  creationTimestamp: '2023-01-17T07:55:11Z'
  generation: 1
  managedFields:
    - apiVersion: integreatly.org/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:datasources': {}
          'f:name': {}
      manager: Mozilla
      operation: Update
      time: '2023-01-17T07:55:11Z'
    - apiVersion: integreatly.org/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:message': {}
          'f:phase': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2023-01-17T07:55:11Z'
  name: ocp-prom
  namespace: grafana
  resourceVersion: '1961660'
  uid: 8a81f86e-b814-416d-a5d6-5a1d92420d49
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: ocp-prom
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          eyJhbGciOiJSUzI1NiIsImtpZCI6IlNrTzZTMzh5QVk4d1g5Tmx6TUhBOEl0VUdtYmROYXBxbU1JTExVZUYxNDgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJncmFmYW5hIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdyYWZhbmEtc2VydmljZWFjY291bnQtdG9rZW4tN3Z2cTUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJkNGQxNDA1LWFhNzUtNGE2Yi1iZTAxLTNlODg0ODdiNzdiMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpncmFmYW5hOmdyYWZhbmEtc2VydmljZWFjY291bnQifQ.HxL_o0ZAfQeL7gvN0EsW0ewl90jd_Vmo54Gzx7qeJsM7mqJai_7mEEdG77mBCE5gA0CByLLl0HsRp3-1ZSv8DJlHIphjfrdEfPo7JR6uJlD1_rHa3aHWompPY1Po2CpMCShWi6Q5ufphx8P4lQhFwEDDdo_O-gVXcMoyBcFtIwwIGrGHi-P1UG96BS4J0NnrmJdmsjsBYhh7vu4OkW_Uq3LLZAVXnaNkrxBQRtqH8qMuv0JccZTz1GeLTt0alHo89LBIoiTjh-RTeC278mLR75whBCyo3UoI6OH9mfa4SBHNpX0ENnxsQuxjEL6UPcBETzV7Su-AQQep-lG5zQbmLBhX4_yzKkoXIQxhA-wwSTe1O_PFvqmE9zeycHwtCECyAjJXiokEa009UC3ym9mvwIszvm5soPQucINLQDRmjNzYNiGPgB8DIundxGqbvR3JtZwOWrw5vTjCfTMlUVbue9oUc-hoaDIbvm0QIYCdHRuqvyk5RqKotoxGiJ5l4TNoBnutXPpFSSrQ1ZBHHYBoZM7G8CvJwdf6uk8nioTJ2U9Rt420HZ0F8Ddvror-GSZC-qhCBeIMlvg2STfZUfzhZVJty1rjmb3RMx_uFMjt5UGR9X7eurwwKVnpMsX_PzNA_uvKZzN5ArpWlfOCy-LLWp1tzw7_eCMCf2ix2GJ99c8
      type: prometheus
      url: >-
        https://thanos-querier-openshift-monitoring.apps.cluster-dqx5g.dqx5g.sandbox2859.opentlc.com
  name: ocp-prom.yaml
status:
  message: ''
  phase: ''
