{{- range .Values.kafkaTopics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafkaCluster }}
spec:
  partitions: {{ .partitions | default 3 }}
  replicas: {{ .replicationFactor | default 3 }}
  config:
    retention.ms: {{ if .config }}{{ (index .config "retention.ms" | default 604800000) | int }}{{ else }}604800000{{ end }}
    segment.bytes: {{ if .config }}{{ (index .config "segment.bytes" | default 1073741824) | int }}{{ else }}1073741824{{ end }}
{{- end }}
