{{- range $users := .Values.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ $users.name }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
{{- range $topic := .topics }}
      - resource:
          type: topic
          name: {{ toYaml $topic }}
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: {{ $topic }}
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: {{ $topic }}
          patternType: literal
        operation: Create
      - resource:
          type: topic
          name: {{ $topic }}
          patternType: literal
        operation: Describe
      # Consumer Groups
      - resource:
          type: group
          name: {{ $users.name }}
          patternType: prefix
        operation: Read
{{- end }}
---
{{- end }}